export const mockData = [
    {
      id: 1,
      title: "Wooden Cafe Table",
      tag: ["home", "best"],
      views: 1234,
      price: 234,
      img: "https://mebel-v-sibiri.ru/files/originals/stolik-kofeynyy-sr-0559-s-143542.jpg",
      isLike: false,
      rating: 4,
      description:
        "Scandinavian simple home side table, modern decor, small snacks for cafes, sofas tables for living room, balcony, C-shaped Sofa table, metal legs",
    },
    {
      id: 2,
      title: "Wireless Headphone",
      tag: ["home", "best"],
      views: 348,
      price: 343,
      img: "https://www.hdretail.ru/upload/iblock/160/160fa37cea09204ec381995fd90d405e.jpg",
      isLike: false,
      rating: 3.5,
      description:
        "One of the latest innovations is the i18 TWS headphones . A perfect combination of sound quality and ease of use. The charging case for the i18 headphones is made of high-quality plastic. It is easy to open and close without any problems.",
    },
    {
      id: 3,
      title: "Leather Watch",
      tag: ["home", "best", "men"],
      views: 9328,
      price: 55,
      img: "https://remobi.ru/media/img/models_small/remont-watch/nika/nika-0362-0-1-46.jpg",
      isLike: false,
      rating: 4.5,
      description:
        "Leather watches just exude class and timelessness. These classic timepieces make the perfect dress watch regardless of movement, watch brands, or style; leather watches are undeniably elegant. You can almost not go wrong with a brown leather strap or even a classic black leather band.",
    },
    {
      id: 4,
      title: "Shoes Without Heels",
      tag: ["home", "best", "women"],
      views: 45,
      price: 227,
      img: "https://main-cdn.sbermegamarket.ru/big2/hlr-system/-51/085/182/511/222/54/100029639788b0.jpg",
      isLike: false,
      rating: 5,
      description:
        "Women's Ballet flats shoes Women's 2021 women's shoes Shoes Women's Autumn Sandals Women's low-heeled Wedding shoes Comemore, white flats without heels, with lacing, pumps for the bride, for summer, 2021",
    },
    {
      id: 5,
      title: "Fashionable Women's Shoes",
      tag: ["women", "best"],
      views: 14356,
      price: 93,
      img: "https://main-cdn.sbermegamarket.ru/big2/hlr-system/317/364/883/113/100/100029647525b0.jpg",
      isLike: false,
      rating: 2.5,
      description:
        "Shoes for girls women's shoes heel new 2021 sandals Comemore women's pointed toe, high-heeled wedding shoes, low-heeled sandals, sandals for party/office, gold/silver, 2021",
    },
    {
      id: 6,
      title: "Stirrer Mug",
      tag: ["home"],
      views: 590,
      price: 26,
      img: "https://ae01.alicdn.com/kf/Hee2bf11f6af1428cb6181d35433b3841i.jpg",
      isLike: false,
      rating: 4,
      description:
        "Automatic Stirrer, Coffee Mugs, Magnetic Water Mixing Cup with Airplane Engine, Smart Milk Mixer, Mixing Cup, Portable Fitness Blender, Gift",
    },
    {
      id: 7,
      title: "Evening Dress For Going Out",
      tag: ["home", "women", "best"],
      views: 3479,
      price: 200,
      img: "https://ae04.alicdn.com/kf/H0cb3664463ee47468c73a7173981b575n/-.jpg_640x640.jpg",
      isLike: false,
      rating: 5,
      description:
        "Women's dress with mesh inserts, black strapless dress, with puffy sleeves, for spring and autumn",
    },
    {
      id: 8,
      title: "Women's dress",
      tag: ["home", "women", "best"],
      views: 2399,
      price: 150,
      img: "https://ae04.alicdn.com/kf/S3e2573440e684a82af6018bd37b19f6a7/KPYTOMOA.jpg_640x640.jpg",
      isLike: false,
      rating: 4.5,
      description:
        "Women's long dress with floral print, front tie and high slit",
    },
    {
      id: 9,
      title: "Women T-shirt with print",
      tag: ["women"],
      views: 239023,
      price: 129,
      img: "https://ae04.alicdn.com/kf/S360fbbd7b58c4b96988a6804019c208cR/KPYTOMOA.jpg_640x640.jpg",
      isLike: false,
      rating: 4.5,
      description:
        "KPYTOMOA Women's fashion with Knotted floral poplin print, vintage women's shirt with V-neck and puffy sleeves, blouses, chic tops",
    },
    {
      id: 10,
      title: "Women's Hoodie",
      tag: ["women"],
      views: 12997,
      price: 50,
      img: "https://ae04.alicdn.com/kf/H1a444f60409e4454be2d929249159fd0f/-.jpg_640x640.jpg",
      isLike: false,
      rating: 5,
      description:
        "Women's Hoodie, Vintage Long Sleeve Sweatshirt, Zipper, Angel Print, Oversize, Y2K, Autumn Gothic Streetwear",
    },
    {
      id: 11,
      title: "Unisex Hoodie with hood",
      tag: ["women", "men", "best", "home"],
      views: 21903,
      price: 60,
      img: "https://ae04.alicdn.com/kf/H39f1637903f7484c8181adaf967a19f5k/-.jpg_640x640.jpg",
      isLike: false,
      rating: 5,
      description:
        "Unisex hoodie with hood, long sleeve and Attack on the Titans print",
    },
    {
      id: 12,
      title: "Men's Baggy Huncher Trousers",
      tag: ["men", "best", "home"],
      views: 12902,
      price: 40,
      img: "https://ae04.alicdn.com/kf/S91c2819de5e144c79d2c633a386eee8cq/Huncher-2022.jpg_640x640.jpg",
      isLike: false,
      rating: 4,
      description:
        "Men's Baggy Huncher Trousers, Summer 2022, Thin Ice silk Joggers, Trousers, Men's Lightweight Quick-drying Casual Suit Trousers for Men",
    },
    {
      id: 13,
      title: "Men's Baggy Huncher Pants",
      tag: ["men", "best", "home"],
      views: 23987,
      price: 30,
      img: "https://ae04.alicdn.com/kf/S1353927300c2454f8e758c00acc4abb6o/Huncher.jpg",
      isLike: false,
      rating: 4.5,
      description:
        "Men's Baggy Huncher Pants, Summer Thin Lightweight Ice Silk Trousers for Running, Quick-drying Trousers, Men's Casual Trousers for Men with Zipper Pockets",
    },
    {
      id: 14,
      title: "Men's Cargo Pants Huncher",
      tag: ["men", "best", "home"],
      views: 1920,
      price: 40,
      img: "https://ae04.alicdn.com/kf/H5a62db467328460ca85a2902816aa4d3V/Huncher-2022.jpg_640x640.jpg",
      isLike: false,
      rating: 5,
      description:
        "Men's Cargo Pants Huncher, Men's Camouflage Joggers 2022, Tactical Military Trousers, Streetwear, Casual Men's Trousers Plus Size 8XL",
    },
    {
      id: 15,
      title: "Lil Peep sweatshirt",
      tag: ["men", "best", "home"],
      views: 2389,
      price: 20,
      img: "https://ae04.alicdn.com/kf/Sd313161fa7da4d1cbad6d26183b0e142C/Lil-Peep.jpg_640x640.jpg",
      isLike: false,
      rating: 4.5,
      description:
        "Lil Peep sweatshirt, sweatshirts, printed skateboard pullovers for men and women, hip-hop streetwear, white sweatshirt, men's oversize pullover, 2022",
    },
    {
      id: 16,
      title: "Classic Women's T-shirt",
      tag: ["women", "best", "home"],
      views: 32345,
      price: 15,
      img: "https://ae04.alicdn.com/kf/S39735394605a4d2699d17d7813493e7cG/-.jpg",
      isLike: false,
      rating: 4,
      description:
        "Classic Women's Pure Cotton T-shirt with Embroidery and Double Fox Head, Summer Fashion Top, Casual Universal Short Sleeve T-shirts Y2K",
    },
    {
      id: 17,
      title: "Men's T-shirt with a round neck",
      tag: ["men", "best", "home"],
      views: 3268,
      price: 17,
      img: "https://ae04.alicdn.com/kf/H410991f1d85c451a87c5f4a1fcb9b04cG/-.jpg_640x640.jpg",
      isLike: false,
      rating: 4.5,
      description:
        "Men's Round neck T-shirt, casual T-shirt with collar, short sleeve T-shirt, fitted silhouette, color white, for summer",
    },
    {
      id: 18,
      title: "Summer men's T-shirt with hood",
      tag: ["men", "best", "home"],
      views: 43898,
      price: 25,
      img: "https://ae04.alicdn.com/kf/H753988b1b1944d199225d3098ff0ef88m/-.jpg_640x640.jpg",
      isLike: false,
      rating: 4.1,
      description:
        "Summer Men's Hooded Tank Top, Sleeveless, for Bodybuilding, Gym, Fitness, High-quality vest, Hip-hop sweatshirt, Men's tops",
    },
   ];
   
   
   
   